# sb2.x ?????Hikari??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/29test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis ??
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.domain

#??????
pagehelper:
  helper-dialect: mysql
